FROM registry.cn-beijing.aliyuncs.com/dobbinsoft/dobbinjdk:8

COPY ./target/netting-im-1.0-SNAPSHOT-jar-with-dependencies.jar main.jar

EXPOSE 8000
EXPOSE 9000

ENV RUN_ENV=dev

CMD ["sh", "-c", "java -jar main.jar --active=${RUN_ENV}" ]