kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-netting-im-sc
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: netting-im
  creationTimestamp: "2023-03-01T17:56:17Z"
  generation: 1
  labels:
    k8s-app: netting-im
    qcloud-app: netting-im
  name: netting-im
  namespace: netting
  selfLink: /apis/apps/v1/namespaces/netting/deployments/netting-im
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: netting-im
      qcloud-app: netting-im
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: netting-im
        qcloud-app: netting-im
    spec:
      containers:
        - image: ${IMAGE}
          imagePullPolicy: Always
          name: netting-im
#          resources:
#            limits:
#              cpu: 1
#              memory: 1124Mi
#            requests:
#              cpu: 1
#              memory: 512Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: netting-im-log
              mountPath: "/home/dobbin/logs"
      volumes:
        - name: netting-im-log
          persistentVolumeClaim:
            claimName: pvc-netting-im-sc
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aliyun
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: k8s-app
#                    operator: In
#                    values:
#                      - netting-im
#              topologyKey: kubernetes.io/hostname
